language: node_js
node_js:
- '5'
- '6.11'
- '7'
- 8.1.3
after_script:
- npm run-script coveralls
deploy:
  provider: npm
  email: npm@ojezu.org
  api_key:
    secure: CL21eQJ9SuLrF9DrZXmvMRrPq2cglePFc3bAqxIbp/Y6/IEeD0T07xdEq2ipd+tuvgtdyasEuGJGVmFRRGsYeO/L6FPcmwgR8SA4k8QfeRitni8tnO8L+MjNC/PoqZn85agMc94Hv+08myZJTX+tE4Ug9hokChTd51z6Pk1LMVJ/OoV9HZojKHcWVhHYmimyM1Ht1q34SINqwfn3h46T8dV/bOmXWrktYsG/mcQSxjFuD/akFP804P0IeQ2u19nlqHqwBIEjgVxNOsB0tb+c1ny/y8i0j1NaGmQm6eAQN0MOeRtNwIGlMTwcisDqW3Vq4mbV6DUKHgEZ6tzE3cDKwaeuE4aodwC6dKrm74d6om5i41AXwVn8PE54HUVX/XRMrVSG5ZCHKjWKdDdIPIBDVlqkn1Nt7LhJYQaqS09NBcO73JRSSQLGfRnGEcUz5QmbbEsUyW3aeeLcOETts3V+rl/LUemUJ5kTijNr5pW1IgKroIZHh+FuLcD96OvVMg1fIFSMQjrbek/cpoy7zyGXdnURLbQp8Girhv+18vGqSJ3UxB8poGeQu8jCSXE9f4Cxw8mH5z738vASbMLl2zVtaSz0kWKr3XrfExI/OZBDWYi/n8xY08pH2ZUYQBzauVVU5HuZObWTAa5A72zkJysBYhzi5YWIdienCaVV1PN6QjY=
  on:
    tags: true
    branch: master
    repo: OJezu/hot-wire
